language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t moz5691/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true moz5691/react-docker npm run test -- --coverage

deploy:
  provider: elaasticbeanstalk
  region:
  app: "react-docker"
  env: "Docker-Env"
  bucket_name:
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
